import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faEnvelopeOpenText, faPhone } from "@fortawesome/free-solid-svg-icons";
import {
  faWhatsapp,
  faFacebook,
  faYoutube,
  faLinkedin,
} from "@fortawesome/free-brands-svg-icons";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import Header from "./component/Header";

export const metadata = {
  title: "TSF foundation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="hidden lg:flex h-10 bg-blue-700 items-center">
          <div className="w-screen flex justify-around ">
            <div>
              <FontAwesomeIcon className="px-1" icon={faEnvelopeOpenText} />
              <a href="mailto: Academy.sciences.TSF@gmail.com">
                Academy.sciences.TSF@gmail.com
              </a>
            </div>
            <div>
              <FontAwesomeIcon className="px-1" icon={faWhatsapp} />
              <a href="https://wa.me/33652806134?text=Bonjour,%20Je%20suis%20intéréssé%20">
                Paris: +33 6 52 80 61 34
              </a>
            </div>
            <div>
              <FontAwesomeIcon className="px-1" icon={faPhone} />
              <a href="tel:0539395140">Rabat: 05 39 39 51 40 </a>
            </div>
          </div>
          <div className="flex justify-end">
            <FontAwesomeIcon className="px-5" icon={faFacebook} />
            <FontAwesomeIcon className="px-5" icon={faYoutube} />
            <FontAwesomeIcon className="px-5" icon={faLinkedin} />
          </div>
        </div>
        <Header />
        

        {children}

        <div className="flex h-screen justify-center items-end">
          <small>
            Copyright &copy; 2023. All rights reserved by
            <span className="text-blue-400">
              Africa Digital Farming school.
            </span>
          </small>
        </div>
      </body>
    </html>
  );
}
