import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { IconProp } from "@fortawesome/react-fontawesome";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export const metadata = {
  title: "TSF foundation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-10 bg-blue-700 items-center">
          <div className="w-1/2 flex justify-between mx-auto">
            <p>
            <FontAwesomeIcon icon={IconProp} />
              <a href="mailto: Academy.sciences.TSF@gmail.com">
                Academy.sciences.TSF@gmail.com
              </a>
            </p>
            <p>
              <a href="https://wa.me/33652806134?text=Bonjour,%20Je%20suis%20intéréssé%20">
                Paris: +33 6 52 80 61 34
              </a>
            </p>
            <p>
              <a href="tel:0539395140">Rabat: 05 39 39 51 40 </a>
            </p>
          </div>
        </div>
        {children}
        <div>
          <small>
            Copyright &copy; 2023. All rights reserved by{" "}
            <span className="text-blue-400"> Africa Digital Farming school. </span>
          </small>
        </div>
      </body>
    </html>
  );
}
